//AUTH ACTIONS
export const SET_USER_INFO = 'SET_USER_INFO';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CONNECTION_ERROR = 'CONNECTION_ERROR';
export const USER_EXISTS_ERROR = 'USER_EXISTS_ERROR';

// GROUP ACTIONS
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const JOIN_GROUP_SUCCESS = 'JOIN_GROUP_SUCCESS';
export const GROUP_EXISTS_ERROR = 'GROUP_EXISTS_ERROR';
export const JOIN_GROUP_ERROR  = 'JOIN_GROUP_ERROR';